/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeadCaptureRequest = IDL.Record({
  'name' : IDL.Text,
  'jobSeeker' : IDL.Bool,
  'internInterest' : IDL.Bool,
  'phone' : IDL.Text,
  'foundingInterest' : IDL.Bool,
  'investor' : IDL.Bool,
});
export const Entry = IDL.Record({
  'submitted' : IDL.Bool,
  'data' : LeadCaptureRequest,
});

export const idlService = IDL.Service({
  'createLeadCaptureRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'getAllRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Entry))],
      ['query'],
    ),
  'isSubmitted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeadCaptureRequest = IDL.Record({
    'name' : IDL.Text,
    'jobSeeker' : IDL.Bool,
    'internInterest' : IDL.Bool,
    'phone' : IDL.Text,
    'foundingInterest' : IDL.Bool,
    'investor' : IDL.Bool,
  });
  const Entry = IDL.Record({
    'submitted' : IDL.Bool,
    'data' : LeadCaptureRequest,
  });
  
  return IDL.Service({
    'createLeadCaptureRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'getAllRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Entry))],
        ['query'],
      ),
    'isSubmitted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };